on:
  push:
    branches:
      - "*"
      - "**/*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_URL: dev.cultureamp.design/${GITHUB_REF##*/}
        with:
          msg: "This branch will be deployed to $BRANCH_URL"
